//! Thin CLI command handlers: parse-free logic that calls foundry-core and does file IO.

use anyhow::Context;
use foundry_core::crypto::SignatureAlgorithm;
use foundry_core::pki::{generate_ec_key, issue_leaf, new_ca};
use std::path::Path;
use std::str::FromStr;

/// `foundry keys generate` — write a fresh EC private key (PKCS#8 PEM).
pub fn keys_generate(alg: &str, out: &Path) -> anyhow::Result<()> {
    let alg = SignatureAlgorithm::from_str(alg)?;
    let km = generate_ec_key(alg)?;
    std::fs::write(out, km.private_pem.as_bytes())
        .with_context(|| format!("writing key to {}", out.display()))?;
    tracing::info!(path = %out.display(), alg = %alg, "generated EC private key");
    println!("OK: wrote key {}", out.display());
    Ok(())
}

/// `foundry cert new-ca` — write a self-signed CA cert + key.
pub fn cert_new_ca(
    common_name: &str,
    out_cert: &Path,
    out_key: &Path,
    days: i64,
) -> anyhow::Result<()> {
    let ca = new_ca(common_name, days)?;
    std::fs::write(out_cert, ca.cert_pem.as_bytes())
        .with_context(|| format!("writing CA cert to {}", out_cert.display()))?;
    std::fs::write(out_key, ca.key_pem.as_bytes())
        .with_context(|| format!("writing CA key to {}", out_key.display()))?;
    tracing::info!(cert = %out_cert.display(), key = %out_key.display(), "generated CA");
    println!("OK: wrote CA cert {} and key {}", out_cert.display(), out_key.display());
    Ok(())
}

/// `foundry cert issue` — issue a leaf cert (+ its key) signed by the given CA.
pub fn cert_issue(
    ca: &Path,
    key: &Path,
    common_name: &str,
    san_dns: &[String],
    out_cert: &Path,
    out_key: &Path,
    days: i64,
) -> anyhow::Result<()> {
    let ca_cert_pem = std::fs::read_to_string(ca)
        .with_context(|| format!("reading CA cert {}", ca.display()))?;
    let ca_key_pem = std::fs::read_to_string(key)
        .with_context(|| format!("reading CA key {}", key.display()))?;
    let leaf = issue_leaf(&ca_cert_pem, &ca_key_pem, common_name, san_dns, days)?;
    std::fs::write(out_cert, leaf.cert_pem.as_bytes())
        .with_context(|| format!("writing leaf cert to {}", out_cert.display()))?;
    std::fs::write(out_key, leaf.key_pem.as_bytes())
        .with_context(|| format!("writing leaf key to {}", out_key.display()))?;
    tracing::info!(cert = %out_cert.display(), key = %out_key.display(), "issued leaf certificate");
    println!("OK: wrote leaf cert {} and key {}", out_cert.display(), out_key.display());
    Ok(())
}

/// `foundry quickstart` — generate a 2-level dev PKI and a ready-to-run config.
/// DEV/TEST ONLY. Not for production.
pub fn quickstart(dir: &Path, out_config: &Path) -> anyhow::Result<()> {
    let keys_dir = dir.join("keys");
    let trust_dir = dir.join("trust");
    std::fs::create_dir_all(&keys_dir)?;
    std::fs::create_dir_all(&trust_dir)?;

    // Root CA (trust anchor).
    let root = new_ca("Foundry Dev Root CA", 3650)?;
    std::fs::write(trust_dir.join("root.pem"), root.cert_pem.as_bytes())?;
    std::fs::write(trust_dir.join("root-key.pem"), root.key_pem.as_bytes())?;

    // One leaf per named key. Each chain file (x5c) holds just the leaf.
    for (name, cn, san) in [
        ("issuer_sdjwt", "Foundry Dev Issuer", "localhost"),
        ("verifier_signing", "Foundry Dev Verifier", "localhost"),
        ("statuslist_signer", "Foundry Dev Status List", "localhost"),
    ] {
        let leaf = issue_leaf(&root.cert_pem, &root.key_pem, cn, &[san.to_string()], 365)?;
        std::fs::write(keys_dir.join(format!("{name}.pem")), leaf.key_pem.as_bytes())?;
        std::fs::write(
            keys_dir.join(format!("{name}-chain.pem")),
            leaf.cert_pem.as_bytes(),
        )?;
    }

    std::fs::write(out_config, QUICKSTART_CONFIG.as_bytes())?;

    tracing::warn!("quickstart PKI is DEV/TEST ONLY — do not use in production");
    println!("OK: wrote dev PKI under {} and config {}", dir.display(), out_config.display());
    println!("   ⚠  DEV/TEST ONLY — self-signed dev PKI, not for production.");
    println!("   Next: foundry serve --config {}", out_config.display());
    Ok(())
}

/// Ready-to-run dev config wired to quickstart's key/cert paths (relative to the config dir).
const QUICKSTART_CONFIG: &str = r#"# Foundry dev config generated by `foundry quickstart`.
# ⚠ DEV/TEST ONLY — uses a self-signed dev PKI. Do NOT use in production.
server:
  wallet_facing:
    public_base_url: https://localhost:8443
    bind: 0.0.0.0:8443
  admin:
    bind: 127.0.0.1:9000
    api_key: dev-admin-key
storage:
  path: ./foundry.db
  transaction_ttl_secs: 600
keys:
  issuer_sdjwt:
    private_key: ./keys/issuer_sdjwt.pem
    x5c: ./keys/issuer_sdjwt-chain.pem
    alg: ES256
  verifier_signing:
    private_key: ./keys/verifier_signing.pem
    x5c: ./keys/verifier_signing-chain.pem
    alg: ES256
  statuslist_signer:
    private_key: ./keys/statuslist_signer.pem
    x5c: ./keys/statuslist_signer-chain.pem
    alg: ES256
trust_anchors:
  - name: foundry-dev-root
    certs: ./trust/root.pem
issuer:
  credential_issuer: https://localhost:8443
  wallet_attestation: { mode: optional }
  key_attestation: { mode: optional }
  status_list:
    enabled: true
    signing_key: statuslist_signer
    list_size: 1048576
    public_base_url: https://localhost:8443/statuslists
credential_types:
  - id: pid
    format: dc+sd-jwt
    vct: https://localhost:8443/vct/pid
    cryptographic_holder_binding: true
    display: [{ name: "Person ID", locale: en-US }]
    claims:
      - path: [given_name]
        selectively_disclosable: true
      - path: [birthdate]
        selectively_disclosable: true
verifier:
  client_id_scheme: x509_san_dns
  signing_key: verifier_signing
  response_encryption: { alg: ECDH-ES, enc: A128GCM }
  transaction_data_hashes_alg: [sha-256]
  named_queries:
    - id: over18
      dcql: { credentials: [] }
"#;
