[package]
name = "foundry"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "foundry"
path = "src/lib.rs"

[[bin]]
name = "foundry"
path = "src/main.rs"

[dependencies]
foundry-core = { path = "../foundry-core" }
foundry-issuer = { path = "../foundry-issuer" }
foundry-verifier = { path = "../foundry-verifier" }
tokio = { workspace = true }
axum = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_html_form = "0.2"
percent-encoding = { workspace = true }
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true }
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
tempfile = "3"
sha2 = { workspace = true }
tower = { version = "0.5", features = ["util"] }
josekit = { workspace = true }
base64 = { workspace = true }
foundry-sd-jwt-vc = { path = "../foundry-sd-jwt-vc" }
foundry-mdoc = { path = "../foundry-mdoc" }
coset = { workspace = true }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
x509-cert = { workspace = true }